//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST10120832Task2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmerProduct
    {
        public int ID { get; set; }
        public string nameOfProduct { get; set; }
        public string typeOfProduct { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> FarmerID { get; set; }
    }
}
