//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST10120832Task2
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string firstName { get; set; }
        public string surname { get; set; }
        public Nullable<long> phoneNum { get; set; }
        public bool isFarmer { get; set; }
        public string password { get; set; }
        public string SALT { get; set; }
    }
}
